<?php

namespace MatiereBundle\Repository;

/**
 * EstDispenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstDispenseRepository extends \Doctrine\ORM\EntityRepository
{
}
